global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0 
  publish_frequency: 20.0
  resolution: 0.05
  static_map: true
  rolling_window: false
  
  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  inflation_layer:
     inflation_radius: 0.5
     cost_scaling_factor: 5.0
     inflate_unknown: true