local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20.0 
  publish_frequency: 20.0
  resolution: 0.05
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  footprint_padding: 0.0

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
  
  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 3.0
    inflate_unknown: true