shutdown_costmaps: false

controller_frequency: 25.0
controller_patience: 5.0 

planner_frequency: 0.0
planner_patience: 0.0 

shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true

recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
  - name: aggresive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

conservative_reset:
  reset_distance: 10.0

rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017

aggresive_reset:
  reset_distance: 0.5